// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "popper"
import "bootstrap"
import "trix"
import "@rails/actiontext"
import "trix"
import "@rails/actiontext"
import "@fortawesome/fontawesome-free"
import "chartkick"
import "Chart.bundle"